services:
  latex:
    image: texlive/texlive:latest
    volumes:
      - ./:/data
    working_dir: /data
    command: >
      latexmk
      -lualatex
      -shell-escape
      -interaction=nonstopmode
      -outdir=output
      -auxdir=output/logs
      -pvc
      main.tex
    restart: unless-stopped